### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/activerecord-associations-video-review#1]
This video reviews the basic functionality of ActiveRecord, and the various associative methods it allows us to implement. Using these methods, we can quickly and easily establish 'has_many' and 'belongs_to' relationships between an 'Artist' class and a 'Song' class. We also survey ActiveRecord's most commonly used constructor and association methods within our console.

**Comment by curiositypaths** [comment]
Thank you for submitting your Suggested Summary!
