### ISSUE TITLE
Share the URL of the site Avi's using?

### ISSUE THREAD

**Issue by walwoodr** [learn-co-curriculum/activerecord-associations-video-review#2]
It'd be great to have the URL of the site that shares all of the association methods. 

I think it's these
- http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-belongs_to
- http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many

**Comment by curiositypaths** [comment]
Hi there,

That is a great idea. We added a reference to the methods.
