### ISSUE TITLE
Suggested Summary and Objectives

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/activerecord-associations-video-review#3]
_Suggested Summary_
- This lesson covers Active Record Associations, what actually happens (under the hood) when we use association macros like _#has_many_ and _#belongs_to_, and how we can use some of the helper methods made available to us once classes have been associated to one another.

_Suggested Objectives_
- Understand what a _UML_ or _entity relationship diagram_ is and how it describes the schema / structure of our database
- Discuss the preference to use higher-level (more abstract) methods, when available; as opposed to lower-level methods and patterns
- Use Active Record Associations to relate two classes to one another and give yourself access to helpful methods from Active Record
- Implement associations between classes using the #has_many and #belongs_to methods
- Discuss naming conventions when using _#has_many_ and _#belongs_to_ and how it further describes the relationship between two objects
- Understand _ActiveRecord::AssociationTypeMismatch_ errors and how they are Active Record trying to protect us from incorrect association implementations (by maintaining type)
- Describing the difference between object initialization (in memory) and when in the object's lifecycle SQL has actually fired to save the object’s information to the database
- Discuss builder methods and how they allow us to pre-associate two objects, or implement other functionality upon initialization (constructor methods)
- Talk about why the shovel method (<<) is very helpful in Active Record; but also needs to be used judiciously and with care, because of inefficiencies
- Understand the similarities between _Class.new_ & _instance.class.build_; and _Class.create_ & _instance.class.create_
- Use #find_by on a specific instance’s collection to search through that specific instance’s collection, instead of the entire class's collection

**Comment by curiositypaths** [comment]
Thank you for submitting your Suggested Summary and Objectives!
