### ISSUE TITLE
Vvideo at beginning of ActiveRecords

### ISSUE THREAD

**Issue by eland05** [learn-co-curriculum/activerecord-associations-video-review#5]
I noticed looking at the curriculum there were 4 video reviews at the end of ActiveRecord Associations and I struggle to watch 4 videos in a row without doing something, so I decided to watch this one before the Associations labs and I found it helpful to have a little more knowledge of how ActiveRecord Associations work before doing the lab, I had a better understanding of what the labs were asking me to do after watching this video. It helped me to stay engaged by watching a video then doing the labs and watching the videos interspersed throughout the labs, it was more of a cycle of watch then apply, instead of just watch all at the end after the labs.

**Comment by curiositypaths** [comment]
Hi there,

We are very glad you found this lesson helpful.
