### ISSUE TITLE
links to the different resources mentioned within the video

### ISSUE THREAD

**Issue by thelittlestschnauzer** [learn-co-curriculum/activerecord-associations-video-review#6]
Avi mentioned a resource within the video and it would be helpful if on the page he could provide the link. He indicated this is a super helpful resource and that we should memorize the methods that belongs_to and has_many provides. I love the videos that Avi provides. He has a knack for allowing people to get into his brain and see/follow his thought process which is invaluable for someone who is learning.

**Comment by curiositypaths** [comment]
Hi there,

That is a great idea. We added a reference to the `has_many` and `belongs_to` method.
