### ISSUE TITLE
Suggested Summary

### ISSUE THREAD

**Issue by thekevinhuang** [learn-co-curriculum/activerecord-associations-video-review#9]
Adding ActiveRecord Associations to our models uses metaprogramming techniques to add methods and relationships between our classes similar to what we have explored in previous lessons.

This video presents a walkthrough of the has_many and belongs_to relationship of ActiveRecord Associations. We use the Artist and Song models to represent these relationships and explore the functionality of some of the methods that ActiveRecord creates for us.

After this video you should be more familiar with accessing information from associated classes as well as using the build and create methods, understanding the difference between the two.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for submitting your Suggested Summary.
